name: Changeset CI

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: Verify Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: |
          corepack enable

      - name: Install dependencies
        run: |
          yarn install

      - name: Check for changeset
        run: yarn changeset status --since=origin/main
