name: docs-ci

on:
  pull_request:
    branches:
      - main
    paths:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: |
          corepack enable

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        working-directory: docs
        run: |
          yarn build
