name: docs-ci

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v3
        with:
          install: false

      - name: Install tools via mise
        run: |
          mise install node

      - name: Enable Corepack
        run: |
          mise exec -- corepack enable

      - name: Install dependencies
        run: |
          mise exec -- yarn install

      - name: Build
        working-directory: docs
        run: |
          mise exec yarn build
